title: 'Assignments for COMP 4720: Intro to AI'
theme: jekyll-theme-primer 
show_downloads: "true"

header:
  overlay_image: /assets/img_1.jpg
  overlay_filter: 0.5 # same as adding an opacity of 0.5 to a black background
  caption: "Photo credit: [**Unsplash**](https://unsplash.com)"
